# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5d2a065d26398474e15e407a7646450244ca6364cfc83f7216a8811a799e19ef467a2f2e392eb803956550c71af6c80e083232b9cf3cad0ddfb493dd9273c40

test:
  secret_key_base: ab56183728de6a6e7dee4decfddb685a2379bc9bbd963deb491afaa16df3ab1145f910fbc2bbe50e07beed8acb34fb92c2b89e8307ada38584ef82d0968ec5dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
